// Tracked on purpose: `expo-env.d.ts` is generated by the Expo CLI and ignored, so a fresh clone (CI) would not know
// the `*.css` modules that `src/app/_layout.tsx` imports. Same one-line reference, committed.
/// <reference types="expo/types" />
